### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by hnicke** [hnicke/sodalite#19]
As this project slowly is leaving its `proof of concept` phase, the code needs to be refactored heavily.

Upcoming tasks:
- [x] Enhance data model
  - [x] add file permissions directly to entry
- [x] Decouple GUI and core: Design slim interface
- [x] Divide core into several classes (extract both file access and db access)

- [x] refactor action hooks
- [x] refactor gui
~~-[ ] use suitable framework to decouple gui from logic - might use RxPy~~
